name: Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        resolver:
          [
            "nightly-2023-06-27",
            "lts-21.0",
            "lts-20.26",
            "lts-19.33",
            "lts-18.28",
            "lts-16.31",
            "lts-14.27",
            "lts-12.26",
            "lts-11.22",
            "lts-9.21",
          ]
        include:
          - resolver: "nightly-2023-06-27"
            os: ubuntu-latest
            ghc: "9.6.2"
            cabal: latest
            stack: latest
          - resolver: "lts-21.0"
            os: ubuntu-latest
            ghc: "9.4.5"
            cabal: latest
            stack: latest
          - resolver: "lts-20.26"
            os: ubuntu-latest
            ghc: "9.2.5"
            cabal: latest
            stack: latest
          - resolver: "lts-19.33"
            os: ubuntu-latest
            ghc: "9.0.2"
            cabal: latest
            stack: latest
          - resolver: "lts-18.28"
            os: ubuntu-latest
            ghc: "8.10.7"
            cabal: latest
            stack: latest
          - resolver: "lts-16.31"
            os: ubuntu-latest
            ghc: "8.8.4"
            cabal: latest
            stack: latest
          - resolver: "lts-14.27"
            os: ubuntu-latest
            ghc: "8.6.5"
            cabal: latest
            stack: latest
          - resolver: "lts-12.26"
            os: ubuntu-latest
            ghc: "8.4.4"
            cabal: latest
            stack: latest
          - resolver: "lts-11.22"
            os: ubuntu-latest
            ghc: "8.2.2"
            cabal: latest
            stack: latest
          - resolver: "lts-9.21"
            os: ubuntu-latest
            ghc: "8.0.2"
            cabal: latest
            stack: latest

    steps:
      - name: Setup GHC
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: ${{ matrix.stack }}
          cabal-version: ${{ matrix.cabal }}

      - name: Clone project
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-

      # This entirely avoids the caching of a GHC version.
      - name: Build and run tests
        run: "stack test --fast --no-terminal --resolver=${{ matrix.resolver }} --system-ghc"
